########################################################################
# Copyright (c) 1988-2018 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 8/8/2018
#
# generic Gcc Makefile for rostra Library librostra
########################################################################


#
# target
#
librostra_LIBTARGET = librostra.${LIBEXT}

########################################################################

#
# user c++ flags
#
librostra_USRCXXFLAGS += \
${rostra_USRCXXFLAGS} \

#
# user defines
#
librostra_USRDEFINES += \
${rostra_USRDEFINES} \

#
# user includes
#
librostra_USRINCLUDES += \
${rostra_USRINCLUDES} \

#
# user libdirs
#
librostra_USRLIBDIRS += \
${rostra_USRLIBDIRS} \

########################################################################

#
# Library .c sources
#
#librostra_LIB_C_SOURCES += \
#${ROSTRA_SRC}/rostra/base/Base.c \

#
# Library .cc sources
#
#librostra_LIB_CC_SOURCES += \
#${ROSTRA_SRC}/rostra/base/Base.cc \

#
# Library .cxx sources
#
#librostra_LIB_CXX_SOURCES += \
#${ROSTRA_SRC}/rostra/base/Base.cxx \

#
# Library .cpp sources
#
librostra_LIB_CPP_SOURCES += \
${ROSTRA_SRC}/xos/platform/platform.cpp \

#
# Library .m sources
#
#librostra_LIB_M_SOURCES += \
#${ROSTRA_SRC}/rostra/base/Base.m \

#
# Library .mm sources
#
#librostra_LIB_MM_SOURCES += \
#${ROSTRA_SRC}/rostra/base/Base.mm \


########################################################################




